### ISSUE TITLE
hashie dependency

### ISSUE THREAD

**Issue by fbjork** [nas/url_shortener#2]
Getting this error when I try bundle install:
Bundler could not find compatible versions for gem "hashie":
  In snapshot (Gemfile.lock):
    hashie (0.4.0)

  In Gemfile:
    linkedin (= 0.3.1) depends on
      hashie (~> 1.0.0)

any chance you could loosen the hashie dependency?

**Comment by nas** [comment]
https://github.com/nas/url_shortener/issues/4
