### ISSUE TITLE
Dependency update  for hashie

### ISSUE THREAD

**Issue by GaryCarneiro** [nas/url_shortener#4]
Hi,
  Can you please fix the dependency to latest hashie ? I am planning to solve dependency issue for lita
See [link](https://github.com/josqu4red/lita-nagios/issues/1) for more details

```bash
url_shortener (>= 0) ruby depends on
      hashie (0.4.0)
```

**Comment by nas** [comment]
thanks for the PR, merged and closing

**Comment by GaryCarneiro** [comment]
Can you build a gem ?
😬

**Comment by nas** [comment]
sorry about that, done
